name: CBS Enterprise CI/CD Pipeline
permissions:
  contents: write
  actions: write
  
on:
  pull_request:
    branches: [development, uat, main]
  push:
    branches: [development, uat, main]

env:
  APP_NAME: cbs-app

jobs:

# ---------------------------
# 1. BUILD + UNIT TEST
# ---------------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Version
        id: version
        run: |
          VERSION="v1.0.${{ github.run_number }}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test

      - name: Build Application
        run: npm run build

      - name: Archive Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/

# ---------------------------
# 2. SECURITY SCAN
# ---------------------------
  security:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Security Scan
        run: |
          npm audit --audit-level=high

# ---------------------------
# 3. DEPLOY TO DEV
# ---------------------------
  deploy-dev:
    if: github.ref == 'refs/heads/development'
    needs: [build, security]
    runs-on: ubuntu-latest

    environment: development

    steps:
      - name: Deploy to Dev Server
        run: echo "Deploying to DEV..."

# ---------------------------
# 4. DEPLOY TO UAT (QA CONTROL)
# ---------------------------
  deploy-uat:
    if: github.ref == 'refs/heads/uat'
    needs: [build, security]
    runs-on: ubuntu-latest

    environment:
      name: uat
      url: https://uat-bank-app.com

    steps:
      - name: Deploy to UAT
        run: echo "Deploying to UAT..."

# ---------------------------
# 5. APPROVAL GATE (TEAM LEAD)
# ---------------------------
  approval-teamlead:
    needs: deploy-uat
    runs-on: ubuntu-latest

    environment:
      name: teamlead-approval

    steps:
      - run: echo "Waiting for Team Lead Approval"

# ---------------------------
# 6. APPROVAL GATE (MANAGEMENT)
# ---------------------------
  approval-management:
    needs: approval-teamlead
    runs-on: ubuntu-latest

    environment:
      name: management-approval

    steps:
      - run: echo "Waiting for Management Approval"

# ---------------------------
# 7. DEPLOY TO PRODUCTION
# ---------------------------
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    needs: approval-management
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://bank-app.com

    steps:
      - name: Deploy to Production
        run: echo "🚀 Deploying to Production..."
